USE f1db
SET NOCOUNT ON;

INSERT INTO [constructors] VALUES (1,'mclaren','McLaren','British','http://en.wikipedia.org/wiki/McLaren');
INSERT INTO [constructors] VALUES (2,'bmw_sauber','BMW Sauber','German','http://en.wikipedia.org/wiki/BMW_Sauber');
INSERT INTO [constructors] VALUES (3,'williams','Williams','British','http://en.wikipedia.org/wiki/Williams_Grand_Prix_Engineering');
INSERT INTO [constructors] VALUES (4,'renault','Renault','French','http://en.wikipedia.org/wiki/Renault_in_Formula_One');
INSERT INTO [constructors] VALUES (5,'toro_rosso','Toro Rosso','Italian','http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso');
INSERT INTO [constructors] VALUES (6,'ferrari','Ferrari','Italian','http://en.wikipedia.org/wiki/Scuderia_Ferrari');
INSERT INTO [constructors] VALUES (7,'toyota','Toyota','Japanese','http://en.wikipedia.org/wiki/Toyota_Racing');
INSERT INTO [constructors] VALUES (8,'super_aguri','Super Aguri','Japanese','http://en.wikipedia.org/wiki/Super_Aguri_F1');
INSERT INTO [constructors] VALUES (9,'red_bull','Red Bull','Austrian','http://en.wikipedia.org/wiki/Red_Bull_Racing');
INSERT INTO [constructors] VALUES (10,'force_india','Force India','Indian','http://en.wikipedia.org/wiki/Racing_Point_Force_India');
INSERT INTO [constructors] VALUES (11,'honda','Honda','Japanese','http://en.wikipedia.org/wiki/Honda_Racing_F1');
INSERT INTO [constructors] VALUES (12,'spyker','Spyker','Dutch','http://en.wikipedia.org/wiki/Spyker_F1');
INSERT INTO [constructors] VALUES (13,'mf1','MF1','Russian','http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO [constructors] VALUES (14,'spyker_mf1','Spyker MF1','Dutch','http://en.wikipedia.org/wiki/Midland_F1_Racing');
INSERT INTO [constructors] VALUES (15,'sauber','Sauber','Swiss','http://en.wikipedia.org/wiki/Sauber');
INSERT INTO [constructors] VALUES (16,'bar','BAR','British','http://en.wikipedia.org/wiki/British_American_Racing');
INSERT INTO [constructors] VALUES (17,'jordan','Jordan','Irish','http://en.wikipedia.org/wiki/Jordan_Grand_Prix');
INSERT INTO [constructors] VALUES (18,'minardi','Minardi','Italian','http://en.wikipedia.org/wiki/Minardi');
INSERT INTO [constructors] VALUES (19,'jaguar','Jaguar','British','http://en.wikipedia.org/wiki/Jaguar_Racing');
INSERT INTO [constructors] VALUES (20,'prost','Prost','French','http://en.wikipedia.org/wiki/Prost_Grand_Prix');
INSERT INTO [constructors] VALUES (21,'arrows','Arrows','British','http://en.wikipedia.org/wiki/Arrows_Grand_Prix_International');
INSERT INTO [constructors] VALUES (22,'benetton','Benetton','Italian','http://en.wikipedia.org/wiki/Benetton_Formula');
INSERT INTO [constructors] VALUES (23,'brawn','Brawn','British','http://en.wikipedia.org/wiki/Brawn_GP');
INSERT INTO [constructors] VALUES (24,'stewart','Stewart','British','http://en.wikipedia.org/wiki/Stewart_Grand_Prix');
INSERT INTO [constructors] VALUES (25,'tyrrell','Tyrrell','British','http://en.wikipedia.org/wiki/Tyrrell_Racing');
INSERT INTO [constructors] VALUES (26,'lola','Lola','British','http://en.wikipedia.org/wiki/MasterCard_Lola');
INSERT INTO [constructors] VALUES (27,'ligier','Ligier','French','http://en.wikipedia.org/wiki/Ligier');
INSERT INTO [constructors] VALUES (28,'forti','Forti','Italian','http://en.wikipedia.org/wiki/Forti');
INSERT INTO [constructors] VALUES (29,'footwork','Footwork','British','http://en.wikipedia.org/wiki/Footwork_Arrows');
INSERT INTO [constructors] VALUES (30,'pacific','Pacific','British','http://en.wikipedia.org/wiki/Pacific_Racing');
INSERT INTO [constructors] VALUES (31,'simtek','Simtek','British','http://en.wikipedia.org/wiki/Simtek');
INSERT INTO [constructors] VALUES (32,'team_lotus','Team Lotus','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (33,'larrousse','Larrousse','French','http://en.wikipedia.org/wiki/Larrousse');
INSERT INTO [constructors] VALUES (34,'brabham','Brabham','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (35,'dallara','Dallara','Italian','http://en.wikipedia.org/wiki/Dallara');
INSERT INTO [constructors] VALUES (36,'fondmetal','Fondmetal','Italian','http://en.wikipedia.org/wiki/Fondmetal');
INSERT INTO [constructors] VALUES (37,'march','March','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO [constructors] VALUES (38,'moda','Andrea Moda','Italian','http://en.wikipedia.org/wiki/Andrea_Moda_Formula');
INSERT INTO [constructors] VALUES (39,'ags','AGS','French','http://en.wikipedia.org/wiki/Automobiles_Gonfaronnaises_Sportives');
INSERT INTO [constructors] VALUES (40,'lambo','Lambo','Italian','http://en.wikipedia.org/wiki/Modena_(racing_team)');
INSERT INTO [constructors] VALUES (41,'leyton','Leyton House','British','http://en.wikipedia.org/wiki/Leyton_House');
INSERT INTO [constructors] VALUES (42,'coloni','Coloni','Italian','http://en.wikipedia.org/wiki/Enzo_Coloni_Racing_Car_Systems');
INSERT INTO [constructors] VALUES (44,'eurobrun','Euro Brun','Italian','http://en.wikipedia.org/wiki/Euro_Brun');
INSERT INTO [constructors] VALUES (45,'osella','Osella','Italian','http://en.wikipedia.org/wiki/Osella');
INSERT INTO [constructors] VALUES (46,'onyx','Onyx','British','http://en.wikipedia.org/wiki/Onyx_(racing_team)');
INSERT INTO [constructors] VALUES (47,'life','Life','Italian','http://en.wikipedia.org/wiki/Life_(Racing_Team)');
INSERT INTO [constructors] VALUES (48,'rial','Rial','German','http://en.wikipedia.org/wiki/Rial_%28racing_team%29');
INSERT INTO [constructors] VALUES (49,'zakspeed','Zakspeed','German','http://en.wikipedia.org/wiki/Zakspeed');
INSERT INTO [constructors] VALUES (50,'ram','RAM','British','http://en.wikipedia.org/wiki/RAM_Racing');
INSERT INTO [constructors] VALUES (51,'alfa','Alfa Romeo','Swiss','http://en.wikipedia.org/wiki/Alfa_Romeo_in_Formula_One');
INSERT INTO [constructors] VALUES (52,'spirit','Spirit','British','http://en.wikipedia.org/wiki/Spirit_(racing_team)');
INSERT INTO [constructors] VALUES (53,'toleman','Toleman','British','http://en.wikipedia.org/wiki/Toleman');
INSERT INTO [constructors] VALUES (54,'ats','ATS','Italian','http://en.wikipedia.org/wiki/ATS_(wheels)');
INSERT INTO [constructors] VALUES (55,'theodore','Theodore','Hong Kong','http://en.wikipedia.org/wiki/Theodore_Racing');
INSERT INTO [constructors] VALUES (56,'fittipaldi','Fittipaldi','Brazilian','http://en.wikipedia.org/wiki/Fittipaldi_%28constructor%29');
INSERT INTO [constructors] VALUES (57,'ensign','Ensign','British','http://en.wikipedia.org/wiki/Ensign_%28racing_team%29');
INSERT INTO [constructors] VALUES (58,'shadow','Shadow','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO [constructors] VALUES (59,'wolf','Wolf','Canadian','http://en.wikipedia.org/wiki/Walter_Wolf_Racing');
INSERT INTO [constructors] VALUES (60,'merzario','Merzario','Italian','http://en.wikipedia.org/wiki/Merzario');
INSERT INTO [constructors] VALUES (61,'kauhsen','Kauhsen','German','http://en.wikipedia.org/wiki/Kauhsen');
INSERT INTO [constructors] VALUES (62,'rebaque','Rebaque','Mexican','http://en.wikipedia.org/wiki/Rebaque');
INSERT INTO [constructors] VALUES (63,'surtees','Surtees','British','http://en.wikipedia.org/wiki/Surtees');
INSERT INTO [constructors] VALUES (64,'hesketh','Hesketh','British','http://en.wikipedia.org/wiki/Hesketh_Racing');
INSERT INTO [constructors] VALUES (65,'martini','Martini','French','http://en.wikipedia.org/wiki/Martini_(cars)');
INSERT INTO [constructors] VALUES (66,'brm','BRM','British','http://en.wikipedia.org/wiki/BRM');
INSERT INTO [constructors] VALUES (67,'penske','Penske','American','http://en.wikipedia.org/wiki/Penske_Racing');
INSERT INTO [constructors] VALUES (68,'lec','LEC','British','http://en.wikipedia.org/wiki/LEC_(Formula_One)');
INSERT INTO [constructors] VALUES (69,'mcguire','McGuire','Australian','http://en.wikipedia.org/wiki/McGuire_(Formula_One)');
INSERT INTO [constructors] VALUES (70,'boro','Boro','Dutch','http://en.wikipedia.org/wiki/Boro_(Formula_One)');
INSERT INTO [constructors] VALUES (71,'apollon','Apollon','Swiss','http://en.wikipedia.org/wiki/Apollon_(Formula_One)');
INSERT INTO [constructors] VALUES (72,'kojima','Kojima','Japanese','http://en.wikipedia.org/wiki/Kojima_Engineering');
INSERT INTO [constructors] VALUES (73,'parnelli','Parnelli','American','http://en.wikipedia.org/wiki/Parnelli');
INSERT INTO [constructors] VALUES (74,'maki','Maki','Japanese','http://en.wikipedia.org/wiki/Maki_(cars)');
INSERT INTO [constructors] VALUES (75,'hill','Embassy Hill','British','http://en.wikipedia.org/wiki/Hill_(constructor)');
INSERT INTO [constructors] VALUES (76,'lyncar','Lyncar','British','http://en.wikipedia.org/wiki/Lyncar');
INSERT INTO [constructors] VALUES (77,'trojan','Trojan','British','http://en.wikipedia.org/wiki/Trojan_(Racing_team)');
INSERT INTO [constructors] VALUES (78,'amon','Amon','New Zealander','http://en.wikipedia.org/wiki/Amon_(Formula_One_team)');
INSERT INTO [constructors] VALUES (79,'token','Token','British','http://en.wikipedia.org/wiki/Token_(Racing_team)');
INSERT INTO [constructors] VALUES (80,'iso_marlboro','Iso Marlboro','British','http://en.wikipedia.org/wiki/Iso_Marlboro');
INSERT INTO [constructors] VALUES (81,'tecno','Tecno','Italian','http://en.wikipedia.org/wiki/Tecno');
INSERT INTO [constructors] VALUES (82,'matra','Matra','French','http://en.wikipedia.org/wiki/Matra');
INSERT INTO [constructors] VALUES (83,'politoys','Politoys','British','http://en.wikipedia.org/wiki/Frank_Williams_Racing_Cars');
INSERT INTO [constructors] VALUES (84,'connew','Connew','British','http://en.wikipedia.org/wiki/Connew');
INSERT INTO [constructors] VALUES (85,'bellasi','Bellasi','Swiss','http://en.wikipedia.org/wiki/Bellasi');
INSERT INTO [constructors] VALUES (86,'tomaso','De Tomaso','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO [constructors] VALUES (87,'cooper','Cooper','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (88,'eagle','Eagle','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO [constructors] VALUES (89,'lds','LDS','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO [constructors] VALUES (90,'protos','Protos','British','http://en.wikipedia.org/wiki/Protos_(constructor)');
INSERT INTO [constructors] VALUES (91,'shannon','Shannon','British','http://en.wikipedia.org/wiki/Shannon_(Formula_One)');
INSERT INTO [constructors] VALUES (92,'scirocco','Scirocco','British','http://en.wikipedia.org/wiki/Scirocco-Powell');
INSERT INTO [constructors] VALUES (93,'re','RE','Rhodesian','http://en.wikipedia.org/wiki/RE_%28automobile%29');
INSERT INTO [constructors] VALUES (94,'brp','BRP','British','http://en.wikipedia.org/wiki/British_Racing_Partnership');
INSERT INTO [constructors] VALUES (95,'porsche','Porsche','German','http://en.wikipedia.org/wiki/Porsche_in_Formula_One');
INSERT INTO [constructors] VALUES (96,'derrington','Derrington','British','http://en.wikipedia.org/wiki/Derrington-Francis');
INSERT INTO [constructors] VALUES (97,'gilby','Gilby','British','http://en.wikipedia.org/wiki/Gilby');
INSERT INTO [constructors] VALUES (98,'stebro','Stebro','Canadian','http://en.wikipedia.org/wiki/Stebro');
INSERT INTO [constructors] VALUES (99,'emeryson','Emeryson','British','http://en.wikipedia.org/wiki/Emeryson');
INSERT INTO [constructors] VALUES (100,'enb','ENB','Belgian','http://en.wikipedia.org/wiki/Ecurie_Nationale_Belge');
INSERT INTO [constructors] VALUES (101,'jbw','JBW','British','http://en.wikipedia.org/wiki/JBW');
INSERT INTO [constructors] VALUES (102,'ferguson','Ferguson','British','http://en.wikipedia.org/wiki/Ferguson_Research_Ltd.');
INSERT INTO [constructors] VALUES (103,'mbm','MBM','Swiss','http://en.wikipedia.org/wiki/Monteverdi_Basel_Motors');
INSERT INTO [constructors] VALUES (104,'behra-porsche','Behra-Porsche','Italian','http://en.wikipedia.org/wiki/Behra-Porsche');
INSERT INTO [constructors] VALUES (105,'maserati','Maserati','Italian','http://en.wikipedia.org/wiki/Maserati');
INSERT INTO [constructors] VALUES (106,'scarab','Scarab','American','http://en.wikipedia.org/wiki/Scarab_(constructor)');
INSERT INTO [constructors] VALUES (107,'watson','Watson','American','http://en.wikipedia.org/wiki/A.J._Watson');
INSERT INTO [constructors] VALUES (108,'epperly','Epperly','American','http://en.wikipedia.org/wiki/Epperly');
INSERT INTO [constructors] VALUES (109,'phillips','Phillips','American','http://en.wikipedia.org/wiki/Phillips_(constructor)');
INSERT INTO [constructors] VALUES (110,'lesovsky','Lesovsky','American','http://en.wikipedia.org/wiki/Lesovsky');
INSERT INTO [constructors] VALUES (111,'trevis','Trevis','American','http://en.wikipedia.org/wiki/Trevis');
INSERT INTO [constructors] VALUES (112,'meskowski','Meskowski','American','http://en.wikipedia.org/wiki/Meskowski');
INSERT INTO [constructors] VALUES (113,'kurtis_kraft','Kurtis Kraft','American','http://en.wikipedia.org/wiki/Kurtis_Kraft');
INSERT INTO [constructors] VALUES (114,'kuzma','Kuzma','American','http://en.wikipedia.org/wiki/Kuzma_(constructor)');
INSERT INTO [constructors] VALUES (115,'vhristensen','Christensen','American','http://en.wikipedia.org/wiki/Christensen_(constructor)');
INSERT INTO [constructors] VALUES (116,'ewing','Ewing','American','http://en.wikipedia.org/wiki/Ewing_(constructor)');
INSERT INTO [constructors] VALUES (117,'aston_martin','Aston Martin','British','http://en.wikipedia.org/wiki/Aston_Martin_in_Formula_One');
INSERT INTO [constructors] VALUES (118,'vanwall','Vanwall','British','http://en.wikipedia.org/wiki/Vanwall');
INSERT INTO [constructors] VALUES (119,'moore','Moore','American','http://en.wikipedia.org/wiki/Moore_(constructor)');
INSERT INTO [constructors] VALUES (120,'dunn','Dunn','American','http://en.wikipedia.org/wiki/Dunn_Engineering');
INSERT INTO [constructors] VALUES (121,'elder','Elder','American','http://en.wikipedia.org/wiki/Elder_(constructor)');
INSERT INTO [constructors] VALUES (122,'sutton','Sutton','American','http://en.wikipedia.org/wiki/Sutton_(constructor)');
INSERT INTO [constructors] VALUES (123,'fry','Fry','British','http://en.wikipedia.org/wiki/Fry_(racing_team)');
INSERT INTO [constructors] VALUES (124,'tec-mec','Tec-Mec','Italian','http://en.wikipedia.org/wiki/Tec-Mec');
INSERT INTO [constructors] VALUES (125,'connaught','Connaught','British','http://en.wikipedia.org/wiki/Connaught_Engineering');
INSERT INTO [constructors] VALUES (126,'alta','Alta','British','http://en.wikipedia.org/wiki/Alta_auto_racing_team');
INSERT INTO [constructors] VALUES (127,'osca','OSCA','Italian','http://en.wikipedia.org/wiki/Officine_Specializate_Costruzione_Automobili');
INSERT INTO [constructors] VALUES (128,'gordini','Gordini','French','http://en.wikipedia.org/wiki/Gordini');
INSERT INTO [constructors] VALUES (129,'stevens','Stevens','American','http://en.wikipedia.org/wiki/Stevens_(constructor)');
INSERT INTO [constructors] VALUES (130,'bugatti','Bugatti','French','http://en.wikipedia.org/wiki/Bugatti');
INSERT INTO [constructors] VALUES (131,'mercedes','Mercedes','German','http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One');
INSERT INTO [constructors] VALUES (132,'lancia','Lancia','Italian','http://en.wikipedia.org/wiki/Lancia_in_Formula_One');
INSERT INTO [constructors] VALUES (133,'hwm','HWM','British','http://en.wikipedia.org/wiki/Hersham_and_Walton_Motors');
INSERT INTO [constructors] VALUES (134,'schroeder','Schroeder','American','http://en.wikipedia.org/wiki/Schroeder_(constructor)');
INSERT INTO [constructors] VALUES (135,'pawl','Pawl','American','http://en.wikipedia.org/wiki/Pawl_(constructor)');
INSERT INTO [constructors] VALUES (136,'pankratz','Pankratz','American','http://en.wikipedia.org/wiki/Pankratz');
INSERT INTO [constructors] VALUES (137,'arzani-volpini','Arzani-Volpini','Italian','http://en.wikipedia.org/wiki/Arzani-Volpini');
INSERT INTO [constructors] VALUES (138,'nichels','Nichels','American','http://en.wikipedia.org/wiki/Nichels');
INSERT INTO [constructors] VALUES (139,'bromme','Bromme','American','http://en.wikipedia.org/wiki/Bromme');
INSERT INTO [constructors] VALUES (140,'klenk','Klenk','German','http://en.wikipedia.org/wiki/Klenk');
INSERT INTO [constructors] VALUES (141,'simca','Simca','French','http://en.wikipedia.org/wiki/Simca');
INSERT INTO [constructors] VALUES (142,'turner','Turner','American','http://en.wikipedia.org/wiki/Turner_(constructor)');
INSERT INTO [constructors] VALUES (143,'del_roy','Del Roy','American','http://en.wikipedia.org/wiki/Del_Roy');
INSERT INTO [constructors] VALUES (144,'veritas','Veritas','German','http://en.wikipedia.org/wiki/Veritas_(constructor)');
INSERT INTO [constructors] VALUES (145,'bmw','BMW','German','http://en.wikipedia.org/wiki/BMW');
INSERT INTO [constructors] VALUES (146,'emw','EMW','East German','http://en.wikipedia.org/wiki/Eisenacher_Motorenwerk');
INSERT INTO [constructors] VALUES (147,'afm','AFM','German','http://en.wikipedia.org/wiki/Alex_von_Falkenhausen_Motorenbau');
INSERT INTO [constructors] VALUES (148,'frazer_nash','Frazer Nash','British','http://en.wikipedia.org/wiki/Frazer_Nash');
INSERT INTO [constructors] VALUES (149,'sherman','Sherman','American','http://en.wikipedia.org/wiki/Sherman_(constructor)');
INSERT INTO [constructors] VALUES (150,'deidt','Deidt','American','http://en.wikipedia.org/wiki/Deidt');
INSERT INTO [constructors] VALUES (151,'era','ERA','British','http://en.wikipedia.org/wiki/English_Racing_Automobiles');
INSERT INTO [constructors] VALUES (152,'butterworth','Aston Butterworth','British','http://en.wikipedia.org/wiki/Aston_Butterworth');
INSERT INTO [constructors] VALUES (153,'cisitalia','Cisitalia','Italian','http://en.wikipedia.org/wiki/Cisitalia');
INSERT INTO [constructors] VALUES (154,'lago','Talbot-Lago','French','http://en.wikipedia.org/wiki/Talbot-Lago');
INSERT INTO [constructors] VALUES (155,'hall','Hall','American','http://en.wikipedia.org/wiki/Hall_(constructor)');
INSERT INTO [constructors] VALUES (156,'marchese','Marchese','American','http://en.wikipedia.org/wiki/Marchese_(constructor)');
INSERT INTO [constructors] VALUES (157,'langley','Langley','American','http://en.wikipedia.org/wiki/Langley_(constructor)');
INSERT INTO [constructors] VALUES (158,'rae','Rae','American','http://en.wikipedia.org/wiki/Rae_(motorsport)');
INSERT INTO [constructors] VALUES (159,'olson','Olson','American','http://en.wikipedia.org/wiki/Olson_(constructor)');
INSERT INTO [constructors] VALUES (160,'wetteroth','Wetteroth','American','http://en.wikipedia.org/wiki/Wetteroth');
INSERT INTO [constructors] VALUES (161,'adams','Adams','American','http://en.wikipedia.org/wiki/Adams_(constructor)');
INSERT INTO [constructors] VALUES (162,'snowberger','Snowberger','American','http://en.wikipedia.org/wiki/Snowberger');
INSERT INTO [constructors] VALUES (163,'milano','Milano','Italian','http://en.wikipedia.org/wiki/Scuderia_Milano');
INSERT INTO [constructors] VALUES (164,'hrt','HRT','Spanish','http://en.wikipedia.org/wiki/Hispania_Racing');
INSERT INTO [constructors] VALUES (167,'cooper-maserati','Cooper-Maserati','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (166,'virgin','Virgin','British','http://en.wikipedia.org/wiki/Virgin_Racing');
INSERT INTO [constructors] VALUES (168,'cooper-osca','Cooper-OSCA','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (169,'cooper-borgward','Cooper-Borgward','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (170,'cooper-climax','Cooper-Climax','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (171,'cooper-castellotti','Cooper-Castellotti','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (172,'lotus-climax','Lotus-Climax','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (173,'lotus-maserati','Lotus-Maserati','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (174,'de_tomaso-osca','De Tomaso-Osca','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO [constructors] VALUES (175,'de_tomaso-alfa_romeo','De Tomaso-Alfa Romeo','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO [constructors] VALUES (176,'lotus-brm','Lotus-BRM','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (177,'lotus-borgward','Lotus-Borgward','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (178,'cooper-alfa_romeo','Cooper-Alfa Romeo','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (179,'de_tomaso-ferrari','De Tomaso-Ferrari','Italian','http://en.wikipedia.org/wiki/De_Tomaso');
INSERT INTO [constructors] VALUES (180,'lotus-ford','Lotus-Ford','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (181,'brabham-brm','Brabham-BRM','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (182,'brabham-ford','Brabham-Ford','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (183,'brabham-climax','Brabham-Climax','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (184,'lds-climax','LDS-Climax','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO [constructors] VALUES (185,'lds-alfa_romeo','LDS-Alfa Romeo','South African','http://en.wikipedia.org/wiki/LDS_(automobile)');
INSERT INTO [constructors] VALUES (186,'cooper-ford','Cooper-Ford','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (187,'mclaren-ford','McLaren-Ford','British','http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO [constructors] VALUES (188,'mclaren-seren','McLaren-Serenissima','British','http://en.wikipedia.org/wiki/Team_McLaren');
INSERT INTO [constructors] VALUES (189,'eagle-climax','Eagle-Climax','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO [constructors] VALUES (190,'eagle-weslake','Eagle-Weslake','American','http://en.wikipedia.org/wiki/Anglo_American_Racers');
INSERT INTO [constructors] VALUES (191,'brabham-repco','Brabham-Repco','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (192,'cooper-ferrari','Cooper-Ferrari','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (193,'cooper-ats','Cooper-ATS','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (194,'mclaren-brm','McLaren-BRM','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO [constructors] VALUES (195,'cooper-brm','Cooper-BRM','British','http://en.wikipedia.org/wiki/Cooper_Car_Company');
INSERT INTO [constructors] VALUES (196,'matra-ford','Matra-Ford','French','http://en.wikipedia.org/wiki/Matra');
INSERT INTO [constructors] VALUES (197,'brm-ford','BRM-Ford','British','http://en.wikipedia.org/wiki/BRM');
INSERT INTO [constructors] VALUES (198,'mclaren-alfa_romeo','McLaren-Alfa Romeo','British','http://en.wikipedia.org/wiki/McLaren_(racing)');
INSERT INTO [constructors] VALUES (199,'march-alfa_romeo','March-Alfa Romeo','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO [constructors] VALUES (200,'march-ford','March-Ford','British','http://en.wikipedia.org/wiki/March_Engineering');
INSERT INTO [constructors] VALUES (201,'lotus-pw','Lotus-Pratt &amp; Whitney','British','http://en.wikipedia.org/wiki/Team_Lotus');
INSERT INTO [constructors] VALUES (202,'shadow-ford','Shadow-Ford','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO [constructors] VALUES (203,'shadow-matra','Shadow-Matra','British','http://en.wikipedia.org/wiki/Shadow_Racing_Cars');
INSERT INTO [constructors] VALUES (204,'brabham-alfa_romeo','Brabham-Alfa Romeo','British','http://en.wikipedia.org/wiki/Brabham');
INSERT INTO [constructors] VALUES (205,'lotus_racing','Lotus','Malaysian','http://en.wikipedia.org/wiki/Lotus_Racing');
INSERT INTO [constructors] VALUES (206,'marussia','Marussia','Russian','http://en.wikipedia.org/wiki/Marussia_F1');
INSERT INTO [constructors] VALUES (207,'caterham','Caterham','Malaysian','http://en.wikipedia.org/wiki/Caterham_F1');
INSERT INTO [constructors] VALUES (208,'lotus_f1','Lotus F1','British','http://en.wikipedia.org/wiki/Lotus_F1');
INSERT INTO [constructors] VALUES (209,'manor','Manor Marussia','British','http://en.wikipedia.org/wiki/Manor_Motorsport');
INSERT INTO [constructors] VALUES (210,'haas','Haas F1 Team','American','http://en.wikipedia.org/wiki/Haas_F1_Team');
INSERT INTO [constructors] VALUES (211,'racing_point','Racing Point','British','http://en.wikipedia.org/wiki/Racing_Point_F1_Team');
INSERT INTO [constructors] VALUES (213,'alphatauri','AlphaTauri','Italian','http://en.wikipedia.org/wiki/Scuderia_AlphaTauri');
INSERT INTO [constructors] VALUES (214,'alpine','Alpine F1 Team','French','http://en.wikipedia.org/wiki/Alpine_F1_Team');