ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN meeting_key INT;
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN session_key INT;
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN sector INT;
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [lap_number] INT;
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [driver_key] INT;
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [flag] VARCHAR(20);
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [scope] VARCHAR(10);
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [category] VARCHAR(10);
ALTER TABLE [SequelFormulaDevTest].[dbo].[raceControl] ALTER COLUMN [message] VARCHAR(300);