INSERT INTO [Ref].[Country] (Country,CountryID)
VALUES
('Germany',1),
('France',2),
('United Kingdom',3),
('New Zealand',4),
('Italy',5),
('Switzerland',6),
('Netherlands',7),
('Malaysia',8),
('South Africa',9),
('United States',10),
('East Germany',11),
('Belgium',12),
('Brazil',13),
('India',14),
('Spain',15),
('Japan',16),
('Ireland',17),
('Russia',18),
('Australia',19),
('Rhodesia',20),
('Mexico',21),
('Canada',22),
('Hong Kong',23),
('Morocco',24),
('Portugal',25),
('Argentina',26),
('Bahrain',27),
('Azerbaijan',28),
('Monaco',29),
('Hungary',30),
('Turkey',31),
('Saudi Arabia',32),
('South Korea',33),
('Qatar',34),
('Singapore',35),
('Austria',36),
('Sweden',37),
('China',38),
('United Arab Emirates',39),
('West Germany',40),
('Thailand',41),
('East Germany, West Germany',42),
('Denmark',43),
('Finland',44),
(' Switzerland',45),
('Uruguay',46),
('Venezuela',47),
('Czech Republic',48),
('Colombia',49),
('Indonesia',50),
('Rhodesia and Nyasaland',51),
('Poland',52),
('Russian Automobile Federation',53),
('Liechtenstein',54),
('Chile',55),
('China',56)